apiVersion: v1
kind: Service
metadata:
  name: postgresql-svc
  labels:
    app: postgresql
spec:
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
  selector:
    app: postgresql