version: "1"
name: redis-cluster

services:
  redis-master:
    image: docker.io/bitnami/redis:7.0
    hostname: redis-master
    env_file: .env-master
    ports:
      - 6379:6379
    volumes:
      - redis_master_data:/bitnami/redis

  redis-slave:
    image: docker.io/bitnami/redis:7.0
    hostname: redis-slave
    env_file: .env-slave
    ports:
      - 6380:6379
    volumes:
      - redis_slave_data:/bitnami/redis
    depends_on:
      - redis-master

volumes:
  redis_master_data:
    driver: local
  redis_slave_data:
    driver: local
