apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: redis-pvc
          persistentVolumeClaim:
            claimName: redis-pvc
      restartPolicy: Always
      containers:
        - name: redis
          image: bitnami/redis:7
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: redis-cm
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 1024Mi
          ports:
            - containerPort: 6379
          startupProbe:
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 10
            tcpSocket: 
              port: 6379
          readinessProbe:
            periodSeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            tcpSocket: 
              port: 6379
          livenessProbe:
            periodSeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            tcpSocket: 
              port: 6379
          volumeMounts:
            - name: redis-pvc
              mountPath: /data
