version: "3"
name: rabbitmq-cluster

services:
  rabbitmq-master:
    image: docker.io/rabbitmq:3-management-alpine
    hostname: rabbitmq-master
    env_file: .env-master
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh

  rabbitmq-slave:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq-slave
    env_file: .env-slave
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    depends_on:
      - rabbitmq-master

  haproxy:
    image: haproxy:1.7
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 15672:15672
      - 5672:5672
    depends_on:
      - rabbitmq-master
      - rabbitmq-slave
