version: "1"
name: rabbitmq

services:
  rabbitmq:
    image: docker.io/rabbitmq:3-management-alpine
    hostname: rabbitmq
    env_file: .env
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
    driver: local
